version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hometest_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - home_network

  web:
    depends_on:
      - mysql
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=hometest_db
      - DB_HOST=mysql
      - JWT_SECRET_KEY=hometest_secret
    networks:
      - home_network

volumes:
  db:

networks:
  home_network:
